name: publish website with mkdocs
on:
  # enable manual trigger via button in GitHub actions
  workflow_dispatch:
  # enable auto trigger based on path and branch
  push:
    # for main branch
    branches:
      - main
    # if something has changed under this directory
    paths:
      - 'docs/**'
jobs:
  build:
    name: deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
      - name: mkdocs gh-deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml

  CWMetricStreamBuild:
    name: CWMetricStream Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: cd CWMetricStreamExporter && cd lambda && go mod download

    - name: Go Build
      run: cd CWMetricStreamExporter && make go_build

    - name: Go Test
      run: cd CWMetricStreamExporter && make go_test

    - name: NPM Build
      run: cd CWMetricStreamExporter && make npm_build

    - name: NPM Lint
      run: cd CWMetricStreamExporter && make npm_lint
      
    - name: NPM Test
      run: cd CWMetricStreamExporter && make npm_test
